collections:
  faq:
  team:
  partners:
    output: true
    permalink: partners/:path/
  events:
    output: true
    permalink: events/:path/
  news:
    output: true
    permalink: news/:path/

defaults:
  - scope:
      path: ""
      type: "partners"
    values:
      layout: "partner"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  permalink: /:num/
  title: ':title - page :num of :max'