collections:
  faq:
  team:
  partners:
    output: true

defaults:
  - scope:
      path: ""
      type: "partners"
    values:
      layout: "partner"
  - scope:
      path: ""
    values:
      layout: "default"